- import_tasks: python.yml
- import_tasks: pycharm.yml
- import_tasks: kraken.yml
- import_tasks: postgis.yml
- import_tasks: chrome_driver.yml
  vars:
    pg_v: "9.6"
    postgis_v: "2.3"
    pg_post_v: "2.3.2+dfsg-1~exp2.pgdg16.04+1"
