- name: Copy pycharm installation file
  unarchive:
    src: /tmp/pycharm-professional-2017.2.3.tar.gz
    dest: /opt
    remote_src: true

- name: developer | Increase inotify watch limit
  copy:
    src: files/60-jetbrains.conf
    dest: /etc/sysctl.d/60-jetbrains.conf
