 - name: Copy pycharm installation file
   unarchive:
     src: files/pycharm-professional-2017.1.5.tar.gz
     dest: /opt
     remote_src: true

- name: developer | Increase inotify watch limit
  copy:
    src: files/60-jetbrains.conf
    dest: /etc/sysctl.d/60-jetbrains.conf