- name: developer | Install Python
  package:
    name: python3
    update_cache: no
    state: present
  with_items:
    - python3
    - python3-pip

- name: developer | Install Pip
  package:
    name: python3-pip
    update_cache: no
    state: present

- name: developer | upgrade pip
  pip:
    name: "{{item}}"
    executable: pip3
    state: forcereinstall
  with_items:
    - pip
    - setuptools
    - virtualenvwrapper

- name: developer | virtualenvwrapper
  pip:
    name: virtualenvwrapper
    executable: pip3
    state: present


- name: developer | Install Geany
  package:
    name: "{{item}}"
    update_cache: no
    state: present
  with_items:
    - geany
    - geany-plugins



