
- include_vars: role_vars.yml

- name: Apt-cache | template file
  template:
    src: templates/aptcache.template
    dest: /etc/apt/apt.conf.d/71aptcache
    owner: root
    group: root
    mode: "u=rw,g=r"
