
- include_vars: role_vars.yml

- uri:
    url: http://{{aptcacheserver}}:{{aptcacheport}}/acng-report.html
    return_content: yes
  ignore_errors: yes
  register: webpage

- name: apt | Clear cache file if not available
  template:
    src: templates/no_aptcache.template
    dest: /etc/apt/apt.conf.d/71aptcache
    owner: root
    group: root
    mode: 0644
  when: "'Apt-Cacher NG maintenance page' not in webpage.content"


- name: apt | Create apt cache file 
  template:
    src: templates/aptcache.template
    dest: /etc/apt/apt.conf.d/71aptcache
    owner: root
    group: root
    mode: 0644
  when: "'Apt-Cacher NG maintenance page' in webpage.content"

