- name: chrome-driver | Check the latest release code
  uri:
    url: https://chromedriver.storage.googleapis.com/LATEST_RELEASE
    status_code: 200
    return_content: yes
  register: chromedriver

- debug:
    msg: "/usr/local/bin/chromedriver-{{chromedriver.content|trim}}"

- stat:
    path: "/usr/local/bin/chromedriver-{{chromedriver.content|trim}}"
  register: sym

- debug:
    msg: "Get chrome driver {{chromedriver.content|trim}}"
  when: sym.stat.islnk is not defined

- name: chrome-driver | Download the latest ChromeDriver release
  get_url:
    url: https://chromedriver.storage.googleapis.com/{{ chromedriver.content|trim }}/chromedriver_linux64.zip
    dest: /usr/local/bin/chromedriver-{{ chromedriver.content|trim }}.zip
    mode: 0755
  when: sym.stat.islnk is not defined

- unarchive:
    src: "/usr/local/bin/chromedriver-{{ chromedriver.content|trim }}.zip"
    dest: /usr/local/bin
    remote_src: True
    mode: 0755
  when: sym.stat.islnk is not defined