- apt_key:
    keyserver: ha.pool.sks-keyservers.net
    id: "68576280"
    state: present

- apt_repository:
    repo: deb http://deb.nodesource.com/node_4.x xenial main
    state: present


- apt:
    name: nodejs
    update_cache: yes
    state: present
