- name: Include vars of stuff.yml into the 'stuff' variable (2.2).
  include_vars:
    file: secrets.yml
    name: secrets

- digital_ocean:
    state: present
    command: droplet
    name: mydroplet
    api_token: "{{ secrets.do_api }}"
    size_id: 1gb
    region_id: sgp1
    image_id: ubuntu-16-04-x64
    wait_timeout: 500
    ssh_key_ids: 6528222
  register: my_droplet

- debug:
    msg: "ID is {{ my_droplet.droplet.id }}"

- debug:
    msg: "IP is {{ my_droplet.droplet.ip_address }}"
