- include_vars: role_vars.yml

- name: postgresql| Configure the PostgreSQL APT key
  apt_key: 
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: "ACCC4CF8"
    state: present

- name: postgresql | Configure the PostgreSQL APT repositories
  apt_repository: 
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ release }}-pgdg main
    state: present

- name: Install PostGIS
  package:
    name: postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}={{ postgis_package_version }}
    update_cache: yes
    state: present
