
- include_vars: role_vars.yml

- uri:
    url: http://{{devpi_server}}:{{devpi_port}}/acng-report.html
    return_content: yes
  ignore_errors: yes
  register: webpage

- name: devpi-client | Create .pip
  file: path=/home/{{item}}/.pip state=directory
  with_items:
    - josh
  when: "'devpi-server' in webpage.content"

- name: devpi-client-config | Create pip config file
  template:
    src: templates/pip.conf
    dest: /home/{{ item }}/.pip/pip.conf
  with_items:
    - josh
  when: "'devpi-server' in webpage.content"


- name: devpi-client-config | Create easy_install config file
  template:
    src: templates/pydistutils.cfg
    dest: /home/{{ item }}/.pydistutils.cfg
  with_items:
    - josh
    when: "'devpi-server' in webpage.content"
