- name: yarn | Get Apt key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: yarn | Add repository
  apt_repository:
    repo: deb http://dl.yarnpkg.com/debian/ stable main
    state: present

- name: yarn | Install yarn
  apt:
    name: yarn
    update_cache: yes
    state: present
