- name: docker | Get Apt key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: docker | Add repository
  apt_repository:
    repo: deb http://apt.dockerproject.org/repo ubuntu-xenial main
    state: present

- name: docker | Install docker-engine
  apt:
    name: docker-engine
    update_cache: yes
    state: present

- name: docker | Copy binary for docker-compose
  copy:
    src: files/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
