- name: docker | Get Apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: docker | Add repository
  apt_repository:
    repo: deb http://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: docker | Install docker-engine
  apt:
    name: docker-ce
    update_cache: yes
    state: present

- name: docker | Install docker-compose
  pip:
    name: docker-compose
    executable: pip3
    state: present